export class Partida{
    id: string;
    nome : string;
    lugar : string;
    data : string;
    descricao : string;
    imagem:string;
    a1:string;
    a2:string;
    a3:string;
    a4:string;
    a5:string;
    a6:string;
    a7:string;
    a8:string;
    a9:string;
    a10:string;
    a11:string;
    a1F:string;
    a2F:string;
    a3F:string;
    a4F:string;
    a5F:string;
    a6F:string;
    a7F:string;
    a8F:string;
    a9F:string;
    a10F:string;
    a11F:string;

    b1:string;
    b2:string;
    b3:string;
    b4:string;
    b5:string;
    b6:string;
    b7:string;
    b8:string;
    b9:string;
    b10:string;
    b11:string;
    b1F:string;
    b2F:string;
    b3F:string;
    b4F:string;
    b5F:string;
    b6F:string;
    b7F:string;
    b8F:string;
    b9F:string;
    b10F:string;
    b11F:string;
    constructor(){}

    setDados(obj : any){
        this.nome = obj.nome;
        this.lugar = obj.lugar;
        this.data = obj.data;
        this.descricao = obj.descricao;
        this.imagem = obj.imagem;
        this.a1 = obj.a1;
        this.a2 = obj.a2;
        this.a3 = obj.a3;
        this.a4 = obj.a4;
        this.a5 = obj.a5;
        this.a6 = obj.a6;
        this.a7 = obj.a7;
        this.a8 = obj.a8;
        this.a9 = obj.a9;
        this.a10 = obj.a10;
        this.a11 = obj.a11;
        this.a1F = obj.a1F;
        this.a2F = obj.a2F;
        this.a3F = obj.a3F;
        this.a4F = obj.a4F;
        this.a5F = obj.a5F;
        this.a6F = obj.a6F;
        this.a7F = obj.a7F;
        this.a8F = obj.a8F;
        this.a9F = obj.a9F;
        this.a10F = obj.a10F;
        this.a11F = obj.a11F;

        this.b1 = obj.b1;
        this.b2 = obj.b2;
        this.b3 = obj.b3;
        this.b4 = obj.b4;
        this.b5 = obj.b5;
        this.b6 = obj.b6;
        this.b7 = obj.b7;
        this.b8 = obj.b8;
        this.b9 = obj.b9;
        this.b10 = obj.b10;
        this.b11 = obj.b11;
        this.b1F = obj.b1F;
        this.b2F = obj.b2F;
        this.b3F = obj.b3F;
        this.b4F = obj.b4F;
        this.b5F = obj.b5F;
        this.b6F = obj.b6F;
        this.b7F = obj.b7F;
        this.b8F = obj.b8F;
        this.b9F = obj.b9F;
        this.b10F = obj.b10F;
        this.b11F = obj.b11F;
    }
}